FloracrestTownNPCHouse2_MapScripts::
	.byte 0


FloracrestTownNPCHouse2_EventScript_Twin1::
# 6 "data/maps/FloracrestTownNPCHouse2/scripts.pory"
	msgbox FloracrestTownNPCHouse2_EventScript_Twin1_Text_0, MSGBOX_NPC
	return


FloracrestTownNPCHouse2_EventScript_Twin2::
# 10 "data/maps/FloracrestTownNPCHouse2/scripts.pory"
	msgbox FloracrestTownNPCHouse2_EventScript_Twin2_Text_0, MSGBOX_NPC
	return


FloracrestTownNPCHouse2_EventScript_Woman::
# 14 "data/maps/FloracrestTownNPCHouse2/scripts.pory"
	msgbox FloracrestTownNPCHouse2_EventScript_Woman_Text_0, MSGBOX_NPC
	return


FloracrestTownNPCHouse2_EventScript_Twin1_Text_0:
# 6 "data/maps/FloracrestTownNPCHouse2/scripts.pory"
	.string "{COLOR RED}I can't wait to go on my own Pokémon\n"
	.string "journey…$"

FloracrestTownNPCHouse2_EventScript_Twin2_Text_0:
# 10 "data/maps/FloracrestTownNPCHouse2/scripts.pory"
	.string "{COLOR RED}I go everywhere with my twin!\nShe's my best friend.$"

FloracrestTownNPCHouse2_EventScript_Woman_Text_0:
# 14 "data/maps/FloracrestTownNPCHouse2/scripts.pory"
	.string "{COLOR RED}You should go check out Professor\n Calla's Pokémon Lab.\pShe's the leading authority on Pokémon\nresearch here in Astaria!$"
