FloracrestTown_MapScripts::
	.byte 0


FloracrestTown_EventScript_PlayersHouseSign::
# 6 "data/maps/FloracrestTown/scripts.pory"
	msgbox FloracrestTown_EventScript_PlayersHouseSign_Text_0, MSGBOX_SIGN
	end


FloracrestTown_EventScript_RivalsHouseSign::
# 11 "data/maps/FloracrestTown/scripts.pory"
	msgbox FloracrestTown_EventScript_RivalsHouseSign_Text_0, MSGBOX_SIGN
	end


FloracrestTown_EventScript_TownSign::
# 16 "data/maps/FloracrestTown/scripts.pory"
	msgbox FloracrestTown_EventScript_TownSign_Text_0, MSGBOX_SIGN
	end


FloracrestTown_EventScript_FatMan::
# 21 "data/maps/FloracrestTown/scripts.pory"
	msgbox FloracrestTown_EventScript_FatMan_Text_0, MSGBOX_NPC
	end


FloracrestTown_EventScript_PlayersHouseSign_Text_0:
# 6 "data/maps/FloracrestTown/scripts.pory"
	.string "{PLAYER}'s House$"

FloracrestTown_EventScript_RivalsHouseSign_Text_0:
# 11 "data/maps/FloracrestTown/scripts.pory"
	.string "Rival's House$"

FloracrestTown_EventScript_TownSign_Text_0:
# 16 "data/maps/FloracrestTown/scripts.pory"
	.string "Floracrest Town\nWhere every journey blooms and new beginnings take root.$"

FloracrestTown_EventScript_FatMan_Text_0:
# 21 "data/maps/FloracrestTown/scripts.pory"
	.string "Astaria is really cozy!\pI moved here from Kalos and it's so peaceful.\pMaybe I should visit the calm seaside too…$"
