FloracrestTownNPCHouse1_MapScripts::
	.byte 0


FloracrestTownNPCHouse1_EventScript_Man::
# 6 "data/maps/FloracrestTownNPCHouse1/scripts.pory"
	msgbox FloracrestTownNPCHouse1_EventScript_Man_Text_0, MSGBOX_NPC
	return


FloracrestTownNPCHouse1_EventScript_Girl::
# 10 "data/maps/FloracrestTownNPCHouse1/scripts.pory"
	msgbox FloracrestTownNPCHouse1_EventScript_Girl_Text_0, MSGBOX_NPC
	return


FloracrestTownNPCHouse1_EventScript_Man_Text_0:
# 6 "data/maps/FloracrestTownNPCHouse1/scripts.pory"
	.string "{COLOR BLUE}I've lived in Astaria for as long as I\n"
	.string "can remember!$"

FloracrestTownNPCHouse1_EventScript_Girl_Text_0:
# 10 "data/maps/FloracrestTownNPCHouse1/scripts.pory"
	.string "{COLOR RED}I heard scientists recently discovered\nsome ancient artifacts.\pHow cool is that!$"
